/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}


// Feature Tasks
// Rolling Dice
// Write a method called roll that accepts an integer n and rolls a six-sided dice n times. The method should return an array containing the values of the rolls.

// roll(4)
// Should return something like:

// [3, 2, 1, 5]
// Contains Duplicates
// Write a method called containsDuplicates that returns true or false depending on whether the array contains duplicate values.

// Calculating Averages
// Write a method that accepts an array of integers and calculates and returns the average of all the values in the array.

// Arrays of Arrays
// Given an array of arrays calculate the average value for each array and return the array with the lowest average.

// // Daily average temperatures for Seattle, October 1-28 2017
// int[][] weeklyMonthTemperatures = {
//   {66, 64, 58, 65, 71, 57, 60},
//   {57, 65, 65, 70, 72, 65, 51},
//   {55, 54, 60, 53, 59, 57, 61},
//   {65, 56, 55, 52, 55, 62, 57}
// };

// Testing
// Use JUnit to write at least one test for each of the Feature Tasks.
// Your tests should ensure that each of your methods work correctly.
// Submission Instructions
// Continue working in your repository for the first 5 labs.
// Work on a non-master branch and make commits appropriately.
// Ensure that you can run ./gradlew test inside of your basiclibrary directory to test your work.
// Update your root README file to include the work you did today.
// Create a pull request to your master branch with your work for this lab.
// Submit the link to that pull request on Canvas. Add a comment with the amount of time you spent on this assignment.